### ISSUE TITLE
Make hibb version independent

### ISSUE THREAD

**Issue by jarirajari** [adewes/have-i-been-bloomed#2]
Problem: hibb uses password file version 2 although version 6 is already available. However, hibb uses 2.0 references, which makes updates difficult.

Solution proposal:
- introduce one variable that contains a (fixed) URL, which means it is relatively easy to change it. wget should use it.
- rename the downloaded file to a version independent name e.g. pwned-passwords.txt.7z using "mv" or "wget -O new_file_name http://your_url.com way"
- replace references containing "pwned-passwords-2.0" with "pwned-passwords"

**Comment by adewes** [comment]
Good point, we could simply update the link as I don't think it's interesting to use the old file.

**Comment by jarirajari** [comment]
Yes, the update would be mainly due to readability, maintainability, and the ease of changing the URL.
